/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: ann55010970637 (https://sketchfab.com/ann55010970637)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/demove-freddy-9eb171b2a5bc4b648ada8648c79db9e8
title: Demove Freddy
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/scene.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[0, -0.6, 0.6]} rotation={[-Math.PI / 2, 0, 0]} scale={0}>
            <group position={[-7.1, -21.38, -59.14]} scale={2.08}>
              <mesh geometry={nodes.Object_6.geometry} material={materials.material} />
            </group>
            <group position={[-7.1, -21.38, -59.14]} scale={2.08}>
              <mesh geometry={nodes.Object_8.geometry} material={materials.material_1} />
            </group>
            <group position={[-7.1, -21.38, -59.14]} scale={2.08}>
              <mesh geometry={nodes.Object_10.geometry} material={materials.material_2} />
            </group>
            <group position={[-7.1, -21.38, -59.14]} scale={2.08}>
              <mesh geometry={nodes.Object_12.geometry} material={materials.material_3} />
            </group>
            <group position={[-7.1, -21.38, -59.14]} scale={2.08}>
              <mesh geometry={nodes.Object_14.geometry} material={materials.material_4} />
            </group>
            <group position={[-7.1, -21.38, -59.14]} scale={2.08}>
              <mesh geometry={nodes.Object_16.geometry} material={materials.material_5} />
            </group>
            <group position={[-7.1, -21.38, -59.14]} scale={2.08}>
              <mesh geometry={nodes.Object_18.geometry} material={materials.material_6} />
            </group>
            <group position={[-7.1, -21.38, -59.14]} scale={2.08}>
              <mesh geometry={nodes.Object_20.geometry} material={materials.material_7} />
            </group>
            <group position={[-7.1, -21.38, -59.14]} scale={2.08}>
              <mesh geometry={nodes.Object_22.geometry} material={materials.material_8} />
            </group>
            <group position={[-7.1, -21.38, -59.14]} scale={2.08}>
              <mesh geometry={nodes.Object_24.geometry} material={materials.material_9} />
            </group>
            <group position={[-7.1, -21.38, -59.14]} scale={2.08}>
              <mesh geometry={nodes.Object_26.geometry} material={materials.material_10} />
            </group>
            <group position={[-7.1, -21.38, -59.14]} scale={2.08}>
              <mesh geometry={nodes.Object_28.geometry} material={materials.material_11} />
            </group>
            <group position={[-7.1, -21.38, -59.14]} scale={2.08}>
              <mesh geometry={nodes.Object_30.geometry} material={materials.material_12} />
            </group>
            <group position={[-7.1, -21.38, -59.14]} scale={2.08}>
              <mesh geometry={nodes.Object_32.geometry} material={materials.material_13} />
            </group>
            <group position={[-7.1, -21.38, -59.14]} scale={2.08}>
              <mesh geometry={nodes.Object_34.geometry} material={materials.material_14} />
            </group>
            <group position={[-7.1, -21.38, -59.14]} scale={2.08}>
              <mesh geometry={nodes.Object_36.geometry} material={materials.material_15} />
            </group>
            <group position={[-7.1, -21.38, -59.14]} scale={2.08}>
              <mesh geometry={nodes.Object_38.geometry} material={materials.material_16} />
            </group>
            <group position={[-7.1, -21.38, -59.14]} scale={2.08}>
              <mesh geometry={nodes.Object_40.geometry} material={materials.material_17} />
            </group>
            <group position={[-7.1, -21.38, -59.14]} scale={2.08}>
              <mesh geometry={nodes.Object_42.geometry} material={materials.material_18} />
            </group>
            <group position={[-7.1, -21.38, -59.14]} scale={2.08}>
              <mesh geometry={nodes.Object_44.geometry} material={materials.material_19} />
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/scene.gltf')
